version: '3.8'
name: efk
services:
  elasticsearch:
    container_name: elastic
    image: elasticsearch:7.17.10
    environment:
      - 'discovery.type=single-node'
    ports:
      - '9200:9200'

  kibana:
    container_name: kibana
    image: kibana:7.17.10
    ports:
      - '5601:5601'

  filebeat:
    container_name: filebeat
    image: elastic/filebeat:7.17.10
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro #config
      - /var/run/docker.sock:/var/run/docker.sock:delegated #enrich logs with extra info of the container
      - /var/lib/docker/containers:/var/lib/docker/containers:ro #logs folder
