filebeat.inputs:
  - type: container
    paths:
      - '/var/lib/docker/containers/*/*.log'
    processors:
      - decode_json_fields:
          fields: ['message']
          target: 'json'
          overwrite_keys: true
      - add_docker_metadata: ~

output.elasticsearch:
  hosts: ['elasticsearch:9200']
  indices:
    - index: 'petclinic-%{[agent.version]}-%{+yyyy.MM.dd}'
      when.or:
        - equals:
            container.name: app

logging.json: true
logging.metrics.enabled: false
